# CS412 - Machine Learning - 2021
## Homework 2
100 pts


## Goal

The goal of this homework is two-fold:

*   Gain experience with neural network approaches
*   Gain experience with the Keras library

## Dataset
You are going to use a house price dataset that we prepared for you, that contains four independent variables (predictors) and one target variable. The task is predicting the target variable (house price) from the predictors (house attributes).


Download the data from SuCourse. Reserve 10% of the training data for validation and use the rest for development (learning your models). The official test data we provide (1,200 samples) should only be used for testing at the end, and not model selection.

## Task 
Build a regressor with a neural network that has only one hidden layer, using the Keras library function calls to predict house prices in the provided dataset.

Your code should follow the given skeleton and try the indicated parameters.

## Preprocessing and Meta-parameters
You should try 10,50 and 100 as hidden node count. 

You should  decide on the learning rate (step size), you can try values such as 0.001, 0.01, 0.1, but you may need to increase if learning is very slow or decrease if you see the loss increase!

You can use either sigmoid or Relu activations for the hidden nodes (indicate with your results) and you should know what to use for the activation for the output layer, input, output layer sizes, and the suitable loss function. 

## Software: 

Keras is a library that we will use especially for deep learning, but also with basic neural network functionality of course.

You may find the necessary function references here: 

http://scikit-learn.org/stable/supervised_learning.html
https://keras.io/api/

When you search for Dense for instance, you should find the relevant function and explained parameters, easily.

## Submission: 

Fill this notebook. Write the report section at the end.

You should prepare a separate pdf document as your homework (name hw1-CS412-yourname.pdf) which consists of the report (Part 8) of the notebook for easy viewing -and- include a link to your notebook from within the pdf report (make sure to include the link obtained from the #share link on top right, **be sure to share with Sabancı University first** as otherwise there will be access problems.). 

##1) Initialize

*   First make a copy of the notebook given to you as a starter.

*   Make sure you choose Connect form upper right.


## 2) Load training dataset

* Load the datasets (train.csv, test.csv) provided on SuCourse on your Google drive and read the datasets using Google Drive's mount functions. 
You may find the necessary functions here: 
https://colab.research.google.com/notebooks/io.ipynb

In [ ]:
from google.colab import drive
drive.mount('/content/drive/') 
# click on the url that pops up and give the necessary authorizations

Mounted at /content/drive/




*   Set your notebooks working directory to the path where the datasets are uploaded (cd is the linux command for change directory) 
*   You may need to use cd drive/MyDrive depending on your path to the datasets on Google Drive. (don't comment the code in the cells when using linux commands)






In [ ]:
import pandas as pd
from os.path import join
path_prefix = "/content/drive/My Drive"

#train_df = pd.read_csv(join(path_prefix, 'train.csv'))

test_df = pd.read_csv(join(path_prefix, 'test.csv'))

* List the files in the current directory.

In [ ]:
ls -a

./  ../  .config/  drive/  sample_data/


##3) Understanding the dataset

There are alot of functions that can be used to know more about this dataset

- What is the shape of the training set (num of samples X number of attributes) ***[shape function can be used]***

- Display attribute names ***[columns function can be used]***

- Display the first 5 rows from training dataset ***[head or sample functions can be used]***

..

In [ ]:
# import the necessary libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

train_df = pd.read_csv(join(path_prefix, 'train.csv'))
# show first 10 elements of the training data
train_df.drop(['view'], axis=1)
train_df.head(10)

sqmtrs  nrooms   view crime_rate          price
0     251       5   west        low  925701.721399
1     211       3   west       high  622237.482636
2     128       5   east        low  694998.182376
3     178       3   east       high  564689.015926
4     231       3   west        low  811222.970379
5     253       5  north       high  766250.032506
6     101       1  north        low  512749.401548
7     242       1  north       high  637010.760148
8     174       5   west       high  638136.374869
9     328       2  south       high  787704.988273

In [ ]:
# print the shape of data

print("Data dimensionality is: ")
print(train_df.shape)
# also give some statistics about the data like mean, standard deviation etc.
print("means")
train_df.mean(axis=0)


Data dimensionality is: 
(4800, 5)
means


sqmtrs       225.033542
nrooms         2.983958
price     725756.960758
dtype: float64

In [ ]:
print("std")
train_df.std(axis=0)

std


sqmtrs        71.851436
nrooms         1.421251
price     151041.121658
dtype: float64

In [ ]:
train_df.describe()

sqmtrs       nrooms         price
count  4800.000000  4800.000000  4.800000e+03
mean    225.033542     2.983958  7.257570e+05
std      71.851436     1.421251  1.510411e+05
min     100.000000     1.000000  3.564985e+05
25%     163.000000     2.000000  6.179536e+05
50%     226.000000     3.000000  7.292999e+05
75%     287.000000     4.000000  8.389284e+05
max     349.000000     5.000000  1.076067e+06

In [ ]:
print(train_df.isnull().sum())
print(test_df.isnull().sum())

sqmtrs        0
nrooms        0
view          0
crime_rate    0
price         0
dtype: int64
sqmtrs        0
nrooms        0
view          0
crime_rate    0
price         0
dtype: int64


##4) Preprocessing Steps

As some of the features (predictive variables) on this dataset are categorical (non-numeric) you need to do some preprocessing for those features.

Please read 7-features.pdf under SuCourse for converting categorical variables to dummy variables. You can use as many **dummy or indicator variables** as there are categories within one feature. You can also look at pandas' get_dummies or keras.utils.to_categorical functions.

In neural networks, scaling of the features are important, because they affect the net input of a neuron as a whole. You should use **MinMax scaler** on sklearn for this task, which scales the variables between 0 and 1 on by default. (Remember that mean-squared error loss function tends to be extremely large with unscaled features.)


In [ ]:
# encode the categorical variables
view_map= {'west':0,'east':1,'south':2,'north':3}
train_df['view']=train_df['view'].replace(view_map)
crime_map= {'low':0,'high':1}
train_df['crime_rate']=train_df['crime_rate'].replace(crime_map)
train_df.head(10)


sqmtrs  nrooms  view  crime_rate          price
0     251       5     0           0  925701.721399
1     211       3     0           1  622237.482636
2     128       5     1           0  694998.182376
3     178       3     1           1  564689.015926
4     231       3     0           0  811222.970379
5     253       5     3           1  766250.032506
6     101       1     3           0  512749.401548
7     242       1     3           1  637010.760148
8     174       5     0           1  638136.374869
9     328       2     2           1  787704.988273

In [ ]:
print(msc.fit(train_df))
print(msc.transform(train_df))

MinMaxScaler()
[[0.6064257  1.         0.         0.         0.7910344 ]
 [0.44578313 0.5        0.         1.         0.36930338]
 [0.1124498  1.         0.33333333 0.         0.47042055]
 ...
 [0.93975904 0.25       0.         1.         0.59777598]
 [0.93172691 0.25       1.         1.         0.58652921]
 [0.57831325 0.75       0.33333333 0.         0.70951032]]


Don't forget the split the training data to obtain a validation set. **Use random_state=42**

In [ ]:
# split 90-10
from sklearn.model_selection import train_test_split

train,train_valid=train_test_split(train_df,test_size=0.1,random_state=42)


##5) Train neural networks on development data and do model selection using the validation data


* Train a neural network with **one hidden layer** (try 3 different values for the number of neurons in that hidden layer, as 25, 50, 100), you will need to correctly choose the optimizer and the loss function that this model will train with. Use batch_size as 64 and train each model for 30 epochs. 

* Train another neural network with two hidden layers with meta-parameters of your choice. Again, use batch_size as 64 and train the model for 30 epochs. 

* **Bonus (5 pts)** Train a KNN or a Decision Tree model with your own choice of meta parameters to predict the house prices.


In [ ]:
label=train.pop('view')

In [ ]:
# train one-hidden layered neural networks
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from statistics import mean

# define your model architecture
layer=[25,50,100]
def model(a,b):
  acc=[]
  for k in layer:

    knn=KNeighborsClassifier(n_neighbors=k)
    scores=cross_val_score(knn, a,b,cv=5,scoring='accuracy')
    acc.append(scores.mean())
  print(acc)

model(train,label)

[0.2634259259259259, 0.2743055555555555, 0.2777777777777778]


In [ ]:
# compile your model with an optimizer
# can not understand optimization
# train one-hidden layered neural networks
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from statistics import mean

from tensorflow import keras
from tensorflow.keras import layers

# define your model architecture
layer=[25,50,100]
def model(a,b):
  acc=[]
  for k in layer:

    knn=KNeighborsClassifier(n_neighbors=k)
    scores=cross_val_score(knn, a,b,cv=5,scoring='accuracy')
    acc.append(scores.mean())
  print(acc)



model(train,label)

[0.2634259259259259, 0.2743055555555555, 0.2777777777777778]


In [ ]:
# fit the model on training data
# train one-hidden layered neural networks
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# define your model architecture
bestlayer=[100]
bestknn=KNeighborsClassifier(n_neighbors=bestlayer)
bestknn.fit(train,label)

pred=bestknn.predict(test_df)

print('acc= ',accuracy_score(label,pred))


TypeError: ignored

In [ ]:
# train a two-hidden layered neural network

# ...


## 6) Test your trained classifiers on the Validation set
Test your trained classifiers on the validation set and print the mean squared errors.


In [ ]:
# tests on validation

#...


## 7) Test your classifier on Test set

- Load test data
- Apply same pre-processing as training data (encoding categorical variables, scaling)
- Predict the labels of testing data **using the best model that you have selected according to your validation results** and report the mean squared error. 

In [ ]:
# test results


In [ ]:
re NNs

##8) Report Your Results

**Notebook should be RUN:** As training and testing may take a long time, we may just look at your notebook results without running the code again; so make sure **each cell is run**, so outputs are there.

**Report:** Write an **1-2 page summary** of your approach to this problem **below**. 

**Must include statements such as those below:**
**(Remove the text in parentheses, below, and include your own report)**

( Include the problem definition: 1-2 lines )

 (Talk about train/val/test sets, size and how split. )

 (Talk about feature extraction or preprocessing.)

**Add your observations as follows** (keep the questions for easy grading/context) in the report part of your notebook.

**Observations**

- Try a few learning rates for N=25 hidden neurons,  train for the indicated amount of epochs. Comment on what happens when learning rate is large or small? What is a good number/range for the learning rate?
Your answer here….

- Use that learning rate and vary the number of hidden neurons for the given values and try the indicated number of epochs. Give the validation mean squared errors for different approach and meta-parameters tried **in a table** and state which one you selected as your model. How many hidden neurons give the best model? 
Your answer here….

- State  what your test results are with the chosen approach and meta-parameters: e.g. "We have obtained the best results on the validation set with the ..........approach using a value of ...... for .... parameter. The result of this model on the test data is ..... % accuracy."" 

- How slow is learning? Any other problems?
Your answer here….

- Any other observations (not needed)

 You can add additional visualization as separate pages if you want, think of them as appendix, keeping the summary to 1-2-pages.

